# -*- coding: utf-8 -*-
from build import *

# =========================================================
# SERVICE DATA (content lifted from the existing built service pages)
# Structure: intro paras, 3 breakdown groups, one educational block.
# No em dashes anywhere.
# =========================================================
SERVICES = [
 {"slug":"residential-electrician","name":"Residential Electrician","icon":"home","img":"onsite-ladder.jpg","focus":"center 20%",
  "card":"Everything around the home: extra power points and lighting, switchboard upgrades, rewiring and fault finding.",
  "h1":"Your trusted local electrician for every job around the home.",
  "hero":"From everyday repairs to full home rewires, Torraca Electrical delivers safe, quality residential electrical services across Hornsby and the North Shore, done right the first time.",
  "stype":"Residential Electrical Services",
  "title":"Residential Electrician Hornsby | Home Electrical Services | Torraca Electrical",
  "meta":"Reliable residential electrician for Hornsby and the North Shore. From power points to full switchboard upgrades, Torraca Electrical gets the job done right. Call today.",
  "intro":[
    "Are you looking for a reliable, friendly and local residential electrician on the North Shore? Torraca Electrical are the local specialists: professional, fully licensed, and trusted by homeowners across the area for everything from a single power point to a full home rewire.",
    "When you choose Torraca Electrical, you can expect prompt, reliable service from a team that genuinely cares about the job they do. We respect your home, your time, and your budget, and we won't leave until the work is done right.",
    "Whether it's a new installation, a repair, or a long-overdue upgrade, we're here to help. Contact the team at Torraca Electrical today for a free quote."],
  "groups":[
    ("Power points, lighting and switches",["Additional GPO power points and USB outlets","Downlight installation and LED upgrades","Ceiling fans and exhaust fans","Outdoor and security lighting","Smart switches and dimmer installation"]),
    ("Switchboards and safety switches",["Switchboard upgrades and replacements","Safety switch (RCD) installation","Circuit breaker upgrades","Surge protection","Meter box upgrades"]),
    ("Rewiring and fault finding",["Full and partial home rewires","Electrical fault diagnosis and repair","Pre-purchase electrical inspections","Smoke alarm installation and testing","Compliance and defect rectification"])],
  "edu_h":"When should you call a residential electrician?",
  "edu_intro":"Electrical issues don't always announce themselves. Some signs are obvious, others are easy to miss until they become a real problem. You should call a licensed electrician if you notice:",
  "edu_list":["Lights flickering or tripping circuit breakers","Power points that spark, feel warm, or don't work","Your switchboard is older than 15 years","You don't have a safety switch installed","You're renovating, extending, or adding a new room","Your smoke alarms are more than 10 years old"],
  "edu_close":"If you're unsure, give us a call. We're happy to give you an honest assessment with no pressure."},

 {"slug":"commercial-electrician","name":"Commercial Electrician","icon":"building","img":"van.jpg",
  "card":"Fit-outs, maintenance, test and tag, and energy-efficient lighting for offices, retail and warehouses. We work around your trading hours.",
  "h1":"Commercial electrical solutions that keep your business running.",
  "hero":"From fit-outs to ongoing maintenance, Torraca Electrical is the trusted commercial electrical partner for businesses across Hornsby and the North Shore. Reliable, responsive and fully licensed.",
  "stype":"Commercial Electrical Services",
  "title":"Commercial Electrician Hornsby | Business Electrical Services | Torraca Electrical",
  "meta":"Trusted commercial electrician for Hornsby and the North Shore. Torraca Electrical handles office fit-outs, maintenance, lighting and upgrades for businesses. Get a quote.",
  "intro":[
    "Are you looking for a reliable, professional commercial electrician on the North Shore? Torraca Electrical works with offices, retail stores, warehouses, restaurants, and businesses of all sizes, delivering electrical solutions that are safe, efficient, and built to last.",
    "We understand that downtime costs money. That's why we work around your schedule, including after hours and weekends when needed, so your operations aren't disrupted. From a single fit-out to an ongoing maintenance agreement, we're the commercial electrical team you can count on.",
    "Ready to work with a commercial electrician who gets the job done right? Contact Torraca Electrical today."],
  "groups":[
    ("Office and retail fit-outs",["New tenancy electrical fit-outs","Power distribution and cabling","Data and communications cabling","Lighting design and installation","Switchboard installation and upgrades"]),
    ("Maintenance and testing",["Scheduled preventative maintenance","Test and tag services","RCD testing and compliance","Emergency lighting testing","Electrical inspections and reports"]),
    ("Lighting and energy efficiency",["Commercial LED lighting upgrades","Sensor and automated lighting controls","Emergency exit lighting","Carpark and external lighting","Energy audits and efficiency upgrades"])],
  "edu_h":"Does your business need a commercial electrician?",
  "edu_intro":"Commercial electrical work is different to residential. It requires an understanding of higher load demands, compliance standards, and the importance of minimising downtime. You should engage a commercial electrician when:",
  "edu_list":["You're fitting out a new tenancy or office space","Your switchboard is outdated or undersized","Equipment keeps tripping breakers","Your test and tag or RCD testing is overdue","You need emergency lighting installed or tested","You want to reduce energy costs with LED lighting"],
  "edu_close":"We work with business owners, property managers, and strata committees across the North Shore. Reach out for an obligation-free consultation."},

 {"slug":"industrial-electrician","name":"Industrial Electrician","icon":"board","img":"switchboard.jpg",
  "card":"3-phase power, motor and machinery connections, and warehouse fit-outs, delivered safely and to AS/NZS 3000.",
  "h1":"Industrial electrical expertise you can rely on, delivered safely and on schedule.",
  "hero":"From 3-phase power to complex machinery installations, Torraca Electrical provides experienced industrial electrical services across Hornsby and Greater Sydney.",
  "stype":"Industrial Electrical Services",
  "title":"Industrial Electrician Hornsby | 3-Phase and Machinery | Torraca Electrical",
  "meta":"Licensed industrial electrician serving Hornsby and the North Shore. Torraca Electrical specialises in 3-phase power, machinery wiring and industrial fit-outs. Call now.",
  "intro":[
    "Industrial electrical work demands a higher level of precision, planning, and safety awareness. Torraca Electrical brings the experience and accreditation needed to handle complex industrial projects, from 3-phase power installations to full industrial fit-outs across the North Shore and Greater Sydney.",
    "We work closely with facility managers, builders, and business owners to ensure every project is delivered safely, on time, and in full compliance with Australian Standards. No matter the scale of the job, we approach it with the same commitment to quality.",
    "Talk to the team today about your industrial electrical requirements."],
  "groups":[
    ("3-phase power and motor connections",["3-phase power supply and distribution","Motor starter and variable speed drive installation","Control panel wiring and assembly","Power factor correction","Electrical load assessments"]),
    ("Machinery and equipment installation",["Industrial machinery wiring and commissioning","Equipment relocation and reconnection","Conveyor and production line electrical","Fault finding and breakdown repairs","Preventative maintenance programs"]),
    ("Industrial fit-outs and compliance",["Warehouse and factory electrical fit-outs","Industrial LED lighting and high-bay upgrades","AS/NZS 3000 wiring compliance","Hazardous area electrical work","Electrical inspection and compliance reports"])],
  "edu_h":"When do you need an industrial electrician?",
  "edu_intro":"Industrial electrical work involves higher voltages, heavier loads, and more complex systems than residential or commercial work, and it carries a higher risk when not handled correctly. You'll need a licensed industrial electrician when:",
  "edu_list":["Installing or commissioning industrial machinery","Upgrading to 3-phase power for heavy equipment","Setting up a new warehouse, factory, or manufacturing space","Carrying out high-bay lighting installations","Performing compliance testing in industrial facilities","Dealing with recurring faults or tripped industrial circuits"],
  "edu_close":"Contact Torraca Electrical to discuss your industrial electrical project. We'll provide a clear scope and competitive quote."},

 {"slug":"ev-charger-installation","name":"EV Charger Installation","icon":"ev","img":"ev-business-hero.jpg","focus":"center 45%",
  "card":"Home and commercial EV chargers installed properly, with the switchboard checked so it charges at full speed.",
  "h1":"Get your EV charger installed by the local experts.",
  "hero":"Torraca Electrical installs EV chargers for homes and businesses across Hornsby and the North Shore. All makes and models, fully licensed, done right the first time.",
  "stype":"EV Charger Installation",
  "title":"EV Charger Installation Hornsby | Home and Commercial | Torraca Electrical",
  "meta":"Licensed EV charger installation for homes and businesses on Sydney's North Shore. Torraca Electrical installs all major brands, fast and hassle-free. Request a quote.",
  "intro":[
    "Switching to an electric vehicle is exciting, but getting the right charger installed properly is essential for safety, performance, and long-term convenience. Torraca Electrical are your local EV charger specialists on the North Shore, installing home and commercial chargers with the same commitment to quality that we bring to every job.",
    "We'll assess your existing switchboard capacity, recommend the right charger for your needs and vehicle, and handle the full installation from start to finish, including any necessary switchboard upgrades. All brands, all models, all done correctly.",
    "Ready to charge at home or set up your business with EV charging? Get in touch today."],
  "groups":[
    ("Home EV charger installation",["Level 2 AC home charger installation","All brands: Tesla, Wallbox, Ocular, Zappi and more","Garage, carport and driveway mounting","Switchboard assessment and upgrade if required","Smart charger setup and app configuration"]),
    ("Commercial EV charging",["Multi-bay commercial EV charging stations","Carpark and strata EV charging installations","Fleet charging infrastructure","Load management and smart charging systems","Access control and payment system integration"]),
    ("Switchboard and power upgrades",["Switchboard capacity assessment","Switchboard upgrades for EV load","Dedicated EV circuit installation","Load balancing for multi-vehicle charging","Solar and battery integration compatibility checks"])],
  "edu_h":"What do you need for an EV charger installation?",
  "edu_intro":"Most homes can accommodate a home EV charger, but there are a few things to check before installation. Here's what's typically involved:",
  "edu_list":["A licensed electrician is required by law, DIY is illegal","Your switchboard may need an upgrade to handle the additional load","A dedicated 32A circuit is recommended for most home chargers","Smart chargers can be configured to charge during off-peak tariffs","Solar system owners can integrate EV charging for maximum savings","Commercial installs may require load management and network approval"],
  "edu_close":"Not sure what you need? We offer a free assessment and quote. Just get in touch with the team."},

 {"slug":"thermal-imaging","name":"Thermal Imaging","icon":"scan","img":"switchboard.jpg",
  "card":"Non-invasive thermal scanning to catch hot spots, loose connections and fire risks before they cost you.",
  "h1":"Catch electrical faults before they become dangerous.",
  "hero":"Torraca Electrical uses professional thermal imaging to identify hidden faults, overloaded circuits and fire risks in switchboards and electrical systems, before they become a problem.",
  "stype":"Thermal Imaging Electrical Inspection",
  "title":"Thermal Imaging Electrician Hornsby | Electrical Scanning | Torraca Electrical",
  "meta":"Detect hidden electrical faults before they cause damage. Torraca Electrical offers professional thermal imaging inspections for homes and businesses on the North Shore.",
  "intro":[
    "Electrical faults don't always trip a breaker or blow a fuse. Many develop silently, in switchboards, behind walls, and in connection points, generating heat that gradually becomes a serious fire risk. Thermal imaging lets us see these faults without opening walls or disturbing your systems.",
    "Our licensed electricians use FLIR-grade thermal cameras to scan your switchboard and electrical systems, identifying hotspots, loose connections, overloaded circuits, and failing components that standard inspections can miss.",
    "Whether you're a homeowner wanting peace of mind or a business requiring an insurance-grade report, Torraca Electrical can help. Contact us to book a thermal imaging inspection."],
  "groups":[
    ("Switchboard and panel scanning",["Full switchboard thermal scan","Hotspot identification in circuit breakers","Loose and corroded connection detection","Overloaded circuit identification","Before and after comparison reporting"]),
    ("Commercial and industrial inspections",["Full facility thermal electrical surveys","Motor and machinery heat mapping","Data centre and server room inspections","High-voltage distribution scanning","Preventative maintenance programs"]),
    ("Insurance and compliance reports",["Formal thermal inspection reports","Insurance-required electrical risk assessments","AS/NZS 3190 compliance documentation","Fault severity grading (low, medium, high)","Recommended rectification works included"])],
  "edu_h":"Why is thermal imaging important?",
  "edu_intro":"Electrical faults are one of the leading causes of house fires in Australia, and many of these fires could have been prevented with early detection. Thermal imaging is the most effective non-invasive way to identify electrical risks. You should consider a thermal inspection if:",
  "edu_list":["Your switchboard is more than 15 years old","Your insurance requires an electrical risk assessment","You're buying or selling a commercial property","You've had repeated fuse or breaker trips","You manage a facility with high electrical demand","You want proactive peace of mind about your electrical system"],
  "edu_close":"A thermal inspection typically takes 1 to 2 hours and provides a detailed written report. Book yours today."},

 {"slug":"emergency-electrician","name":"Emergency Electrician","icon":"alert","img":"van.jpg","emergency":True,
  "card":"Power out, sparking, or a burning smell? We respond 24/7 across the North Shore and make it safe, fast.",
  "h1":"Electrical emergency? We're on call right now.",
  "hero":"Power out, sparking wires, or a safety hazard? Torraca Electrical is available around the clock, 24 hours a day, 7 days a week, for urgent electrical emergencies across Hornsby and the North Shore.",
  "stype":"Emergency Electrical Services",
  "title":"Emergency Electrician Hornsby | 24/7 Electrical Response | Torraca Electrical",
  "meta":"Electrical emergency on the North Shore? Torraca Electrical is available 24/7 for urgent faults, power outages and safety hazards. Call now, we're always ready.",
  "intro":[
    "When an electrical emergency strikes, you need someone you can trust to respond quickly, safely, and without delay. Torraca Electrical operates 24 hours a day, 7 days a week, including weekends and public holidays, to get to you when it matters most.",
    "Our emergency-qualified electricians are equipped to assess the situation, make it safe, and restore power as quickly as possible. We won't leave until the job is done and you're safe.",
    "Don't wait with a dangerous electrical situation. Call Torraca Electrical now. We're ready."],
  "groups":[
    ("Power outages and tripped breakers",["Complete power outage diagnosis","Tripped safety switch or circuit breaker reset","Overloaded circuit identification and repair","Switchboard fault finding and rectification","Network fault vs internal fault assessment"]),
    ("Electrical hazards and safety issues",["Sparking or arcing power points and switches","Burning smell from electrical fittings","Exposed or damaged wiring","Electric shock incidents and safety isolation","Smoke or signs of electrical fire"]),
    ("Storm damage and after-hours repairs",["Storm damage to switchboards and service lines","Fallen power lines and emergency isolation","Water ingress into electrical systems","After-hours repairs for homes and businesses","Temporary supply arrangements if needed"])],
  "edu_h":"What is an electrical emergency?",
  "edu_intro":"Not sure if your situation is an emergency? If in doubt, treat it as one. Call us immediately if you experience any of the following:",
  "edu_list":["Complete loss of power to your home or business","Visible sparking, arcing, or burning from any fitting","A burning smell with no obvious cause","An electric shock, however minor","A safety switch that won't reset","Storm damage involving your electrical system or meter box"],
  "edu_close":"While waiting for us to arrive: switch off the affected circuits at your switchboard if safe to do so, keep clear of any exposed wiring, and if you smell burning, leave the premises and call 000 first."},

 {"slug":"strata-property-maintenance","name":"Strata and Property","icon":"key","img":"van.jpg",
  "card":"Responsive maintenance for strata and property managers: common areas, compliance and reports, handled.",
  "h1":"The electrical partner your strata or property portfolio can rely on.",
  "hero":"Torraca Electrical works with strata managers, real estate agents and property managers across the North Shore, providing prompt, professional electrical maintenance and support for residential and commercial properties.",
  "stype":"Strata Electrical Services",
  "title":"Strata Electrician Hornsby | Property Management Electrical | Torraca Electrical",
  "meta":"Trusted strata and property management electrician on Sydney's North Shore. Torraca Electrical is responsive, reliable and fully licensed for strata maintenance. Get in touch.",
  "intro":[
    "Managing a strata property or property portfolio means dealing with electrical issues across multiple lots, common areas, and tenancies, often under time pressure with multiple stakeholders to keep happy. Torraca Electrical understands the demands of strata and property management, and we're set up to make your job easier.",
    "We respond quickly, communicate clearly, and provide the documentation you need, including compliance certificates and detailed job reports, so you can close out maintenance requests with confidence.",
    "Whether it's a routine maintenance visit or an urgent after-hours call-out, we're the strata electrical team the North Shore trusts. Get in touch to discuss an ongoing maintenance arrangement."],
  "groups":[
    ("Common area and carpark lighting",["Common area lighting maintenance and upgrades","Carpark and basement lighting installation","LED lighting upgrades for energy savings","Sensor and timer controls for common areas","Emergency exit lighting testing and maintenance"]),
    ("Strata maintenance and compliance",["Routine strata electrical maintenance programs","RCD testing and compliance for common areas","Switchboard audits and upgrades","Defect rectification and building compliance reports","Annual safety inspections"]),
    ("Property manager support",["Tenant electrical repairs and fault finding","Between-tenancy electrical checks","Smoke alarm installation and compliance","Detailed job reports for strata records","Priority scheduling for managed properties"])],
  "edu_h":"What are your electrical obligations as a strata manager?",
  "edu_intro":"Strata managers and owners corporations have specific legal obligations when it comes to electrical safety in common areas and shared systems. These include:",
  "edu_list":["Maintaining common area lighting and electrical systems","Ensuring emergency lighting is tested every 6 months","RCD (safety switch) testing in common area switchboards","Smoke alarm compliance in common areas","Addressing any electrical defects identified in building reports","Providing compliant electrical infrastructure for tenants"],
  "edu_close":"Torraca Electrical can set up a maintenance schedule to keep your property compliant year-round, taking the burden off your plate. Get in touch to discuss an arrangement that suits your portfolio."},

 {"slug":"sports-field-lighting","name":"Sports Field Lighting","icon":"bulb","img":"park-trench.jpg","focus":"center 42%",
  "card":"LED sports field and court lighting designed to standard, from lux calcs and poles to controls and maintenance.",
  "h1":"High-performance sports lighting that lets the game go on.",
  "hero":"Torraca Electrical designs and installs LED sports lighting for ovals, courts, fields and multi-use facilities across Hornsby and the North Shore. Built for performance, efficiency and long-term reliability.",
  "stype":"Sports Field Lighting Installation",
  "title":"Sports Field Lighting Hornsby | LED Sports Lighting | Torraca Electrical",
  "meta":"Professional LED sports field lighting installation across Sydney's North Shore. Torraca Electrical designs and installs lighting for clubs, councils and facilities. Get a quote.",
  "intro":[
    "Whether you're a local sporting club, a local council, or a multi-sport facility, the right lighting system transforms your venue, extending usable hours, improving player visibility, and reducing long-term energy costs. Torraca Electrical brings the technical expertise to design and install sports lighting systems that meet Australian Standards and your specific lux requirements.",
    "We handle everything from the initial design and pole installation to the electrical supply, control systems, and ongoing maintenance, working around your schedule to minimise disruption to your users.",
    "Ready to upgrade your facility's lighting? Contact us for a consultation and free design quote."],
  "groups":[
    ("LED sports lighting design and supply",["Lighting design to AS/NZS 2560 standards","Lux level calculations for your sport and level","LED fixture selection and specification","Council and authority submission support","Photometric modelling and reporting"]),
    ("Pole and floodlight installation",["Sports lighting pole supply and installation","Foundation design and concrete works","LED floodlight mounting and aiming","Underground cabling and switchboard connection","Network provider approval and coordination"]),
    ("Controls, timing and maintenance",["Timer and automated control system installation","Remote access and app-based control options","Coin-operated and booking system integration","Ongoing maintenance and lamp replacement","Fault response and emergency repair"])],
  "edu_h":"What sports facilities can Torraca light?",
  "edu_intro":"Our sports lighting experience covers a wide range of facility types across the North Shore and Greater Sydney:",
  "edu_list":["Cricket ovals and multi-use sports fields","AFL, rugby, soccer, and football grounds","Tennis courts and netball courts","Basketball courts, indoor and outdoor","Athletics tracks and multi-sport precincts","School and council sporting facilities"],
  "edu_close":"Each project is different, so we start with a site assessment and lux report to ensure the lighting design meets your sport's requirements. Get in touch to arrange a free consultation."},

 {"slug":"landscape-lighting","name":"Landscape Lighting","icon":"tree","img":"lighting.jpg",
  "card":"Garden, path, pool and feature lighting designed and installed safely, wired to last outdoors.",
  "h1":"Beautiful outdoor lighting, installed safely by your local electricians.",
  "hero":"From garden path lights to dramatic feature lighting, Torraca Electrical designs and installs landscape lighting that transforms your outdoor spaces. Safely wired, beautifully executed, built to last.",
  "stype":"Landscape Lighting Installation",
  "title":"Landscape Lighting Hornsby | Outdoor and Garden Lighting | Torraca Electrical",
  "meta":"Transform your outdoor space with expert landscape lighting from Torraca Electrical. Garden, pool and feature lighting installed across Sydney's North Shore. Get a quote.",
  "intro":[
    "Good landscape lighting does more than look beautiful. It adds security, extends the usable hours of your outdoor spaces, and can significantly increase the street appeal and value of your property. Torraca Electrical works with homeowners across the North Shore to design and install outdoor lighting systems that are as practical as they are stunning.",
    "From a simple path light installation to a full outdoor entertainment area lighting design, we handle all the electrical work safely and to the highest standards, with zero compromise on quality or finish.",
    "Ready to transform your outdoor space? Contact us for a free consultation and quote."],
  "groups":[
    ("Garden and path lighting",["Garden bed and feature plant uplighting","Path, driveway and step lighting","Low-voltage garden lighting systems","In-ground and spike-mounted LED fixtures","Timer and dusk-to-dawn control installation"]),
    ("Pool and entertainment lighting",["Pool surrounds and deck lighting","Outdoor entertainment area lighting","Pergola, alfresco and gazebo lighting","Underwater pool and spa light installation","Festoon and decorative lighting wiring"]),
    ("Security and sensor lighting",["Motion sensor security light installation","Driveway and perimeter floodlighting","Smart outdoor lighting and app control","CCTV integration lighting support","Commercial exterior and facade lighting"])],
  "edu_h":"Why use a licensed electrician for landscape lighting?",
  "edu_intro":"Outdoor electrical work involves additional hazards: weather exposure, water, underground cabling, and safety considerations that don't apply indoors. Attempting outdoor lighting without a licensed electrician can be dangerous and may void your home insurance. Here's why it matters:",
  "edu_list":["Outdoor circuits must be protected by safety switches (RCDs)","Pool lighting must comply with strict AS/NZS 3000 requirements","Underground cabling must be correctly installed and protected","All outdoor fittings must be rated for their environment (IP rating)","Incorrectly installed outdoor lighting is a fire and electrocution risk","Only licensed electricians can legally install permanent outdoor wiring"],
  "edu_close":"Torraca Electrical will ensure your landscape lighting is not only stunning but completely safe and compliant. Get in touch to discuss your vision."},
 {"slug":"level-2-asp-electrician","name":"Level 2 ASP Electrician","icon":"bolt","img":"service-overhead.jpg","focus":"center 32%",
  "card":"Network-side work most electricians cannot legally touch: new connections, consumer mains, metering and service lines. Accreditation no. 5760.",
  "h1":"Level 2 ASP Electrician for Ausgrid Connections",
  "hero":"Torraca Electrical is an accredited Level 2 Authorised Service Provider, no. 5760. That means we can do the network-side work a standard electrician is not licensed to touch, and do it in the same visit as the rest of the job.",
  "stype":"Level 2 ASP Electrical Services",
  "title":"Level 2 ASP Electrician Hornsby | Ausgrid Connections | Torraca Electrical",
  "meta":"Accredited Level 2 ASP electrician, no. 5760, for Hornsby and the North Shore. New connections, consumer mains, metering and service lines, handled by one team. Call now.",
  "intro":[
    "Most electricians stop at the meter. Anything on the network side, the service line from the pole, the consumer mains, the metering, has to be done by a Level 2 Authorised Service Provider. If your electrician is not Level 2, they have to sub it out, which adds a trade, a delay and a markup.",
    "We hold that accreditation ourselves. So when a job needs a new connection, an upgraded service line, a metering change or a fault repaired on the incoming supply, we handle it end to end, including the paperwork with Ausgrid."],
  "groups":[
    ("Connections and service lines",["New underground service connections","New overhead service connections","Service line repairs and reconnections","Point of attachment and private pole work","Temporary builder's supply"]),
    ("Consumer mains and metering",["Consumer mains upgrades, single phase","Consumer mains upgrades, three phase","Metering installations and alterations","Disconnection and reconnection of supply","Fault repair on the incoming supply"]),
    ("Supply for bigger loads",["Mains upgrades to support a switchboard upgrade","Supply for EV chargers and three-phase renos","Load assessment on the incoming supply","Coordination and all paperwork with Ausgrid","One team from the street to the powerpoint"])],
  "edu_h":"Do you need a Level 2 electrician?",
  "edu_intro":"Anything on the network side of the meter has to be done by a Level 2 Authorised Service Provider. You need one when:",
  "edu_list":["You are connecting a new build or knock-down rebuild to the grid","Your consumer mains need upgrading to carry more load","A storm or age has damaged your service line","You are moving from single phase to three phase","Supply needs disconnecting and reconnecting for works","Your metering needs installing or altering"],
  "edu_close":"Not sure if your job is network-side? Call us and describe it. We will tell you straight away, and because we are a full electrical contractor as well as Level 2, we can handle the whole job from the street to the last powerpoint."},
]
SVC_BY_SLUG={s["slug"]:s for s in SERVICES}

# =========================================================
# SUBURB DATA
# Each suburb carries: region, unique hook + intro + local housing note,
# and a "near" list of real neighbouring suburbs (slugs) for the internal
# link mesh. Intros are bespoke per suburb, not token swaps.
# =========================================================
# To give a suburb its own hero photo: put the image in assets/img/ and add
#   "photo":"electrician-hornsby.jpg"  to that suburb below.
# No "photo" key = shared hero-van.jpg fallback. Best shot: the team on a job in that suburb.
SUBURBS=[
 # ---------------- NORTH SHORE ----------------
 {"slug":"electrician-hornsby","name":"Hornsby","pc":"2077","region":"North Shore",
  "near":["electrician-asquith","electrician-waitara","electrician-mount-colah","electrician-normanhurst"],
  "hook":"the hub of the Upper North Shore",
  "intro":"Hornsby is home ground for us. From the townhouses and units around the CBD to the older brick homes on the leafy streets toward Waitara and Asquith, we know the housing stock and the boards that come with it. Plenty of Hornsby homes are still running switchboards from a different era, and that is where a lot of our work starts.",
  "local":"a mix of post-war brick homes, newer unit blocks near the station, and family homes toward Waitara and Mount Colah"},
 {"slug":"electrician-asquith","name":"Asquith","pc":"2077","region":"North Shore",
  "near":["electrician-hornsby","electrician-mount-colah","electrician-berowra","electrician-waitara"],
  "hook":"just north of Hornsby",
  "intro":"Asquith sits right on our doorstep, so callouts here are quick. It is a settled residential pocket with a lot of original family homes, which means switchboard upgrades, added circuits and the odd Level 2 job on an ageing supply are the bread and butter.",
  "local":"established family homes and a growing number of renovations and knock-down rebuilds"},
 {"slug":"electrician-berowra","name":"Berowra","pc":"2081","region":"North Shore",
  "near":["electrician-mount-colah","electrician-asquith","electrician-hornsby"],
  "hook":"our registered home base",
  "intro":"Berowra is where we are based, so nobody covers it faster. The bushland setting brings its own electrical realities: longer service runs, older supply on some streets, and outdoor lighting that has to stand up to the elements. We handle all of it, including the network-side work most sparkies cannot.",
  "local":"homes on larger bush blocks, longer service runs and plenty of outdoor lighting"},
 {"slug":"electrician-mount-colah","name":"Mount Colah","pc":"2079","region":"North Shore",
  "near":["electrician-asquith","electrician-berowra","electrician-hornsby"],
  "hook":"between Hornsby and Berowra",
  "intro":"Mount Colah is minutes from base, sitting between Hornsby and Berowra along the rail line. It is solid family-home territory, and much of that housing is at the age where boards, mains and lighting are due an upgrade. We look at the whole setup so you are not fixing it piece by piece.",
  "local":"established family homes on the ridge between the national parks"},
 {"slug":"electrician-waitara","name":"Waitara","pc":"2077","region":"North Shore",
  "near":["electrician-hornsby","electrician-wahroonga","electrician-normanhurst","electrician-asquith"],
  "hook":"right beside Hornsby",
  "intro":"Waitara is dense around the station, with a lot of apartment and unit stock alongside older houses toward Wahroonga. That mix means we do everything from strata common-area maintenance to house rewires within a few streets. Being minutes from base, callouts here are quick.",
  "local":"high-density units near the station and older houses toward the Wahroonga side"},
 {"slug":"electrician-normanhurst","name":"Normanhurst","pc":"2076","region":"North Shore",
  "near":["electrician-thornleigh","electrician-waitara","electrician-wahroonga","electrician-pennant-hills"],
  "hook":"a settled pocket between Hornsby and Thornleigh",
  "intro":"Normanhurst is quiet, established family-home country close to base. Most of the housing is at the age where switchboards, added circuits and lighting are due attention together. We look at the lot and plan it as one job so you are not booking a string of callouts.",
  "local":"established family homes on quiet residential streets"},
 {"slug":"electrician-thornleigh","name":"Thornleigh","pc":"2120","region":"North Shore",
  "near":["electrician-normanhurst","electrician-pennant-hills","electrician-hornsby","electrician-west-pennant-hills"],
  "hook":"on the western side of the Hornsby line",
  "intro":"Thornleigh is solid residential with a light-industrial strip along the highway, so we work both sides: home switchboards, reno wiring and lighting, plus fit-outs and maintenance for the businesses in the Pioneer Avenue pocket. One team covers both.",
  "local":"family homes plus a light-industrial and commercial strip along the highway"},
 {"slug":"electrician-pennant-hills","name":"Pennant Hills","pc":"2120","region":"North Shore",
  "near":["electrician-thornleigh","electrician-normanhurst","electrician-west-pennant-hills","electrician-cherrybrook"],
  "hook":"on the western edge of the Hornsby area",
  "intro":"Pennant Hills is settled, established and close to base. The homes here are largely family homes of an age where switchboards, added circuits and lighting upgrades are common. We assess the whole setup so the work holds up rather than needing a repeat visit.",
  "local":"established family homes and tree-lined residential streets"},
 {"slug":"electrician-wahroonga","name":"Wahroonga","pc":"2076","region":"North Shore",
  "near":["electrician-turramurra","electrician-normanhurst","electrician-waitara","electrician-pymble"],
  "hook":"the top of the Upper North Shore",
  "intro":"Wahroonga has some of the finest homes on the North Shore, and they deserve electrical work to match. We do a lot of renovation and high-end residential work here, where the switchboard, the lighting design and the data all need to be planned properly rather than patched.",
  "local":"heritage and high-end homes, many mid-renovation or extension"},
 {"slug":"electrician-turramurra","name":"Turramurra","pc":"2074","region":"North Shore",
  "near":["electrician-wahroonga","electrician-pymble","electrician-st-ives","electrician-gordon"],
  "hook":"a leafy Upper North Shore suburb",
  "intro":"Turramurra is classic Upper North Shore: large blocks, established homes and owners who want the job done properly the first time. That suits how we work. Switchboard upgrades, full-home lighting, EV chargers and reno wiring make up most of what we do here.",
  "local":"large family homes on established blocks, often with pools and outdoor areas to light"},
 {"slug":"electrician-pymble","name":"Pymble","pc":"2073","region":"North Shore",
  "near":["electrician-gordon","electrician-turramurra","electrician-st-ives","electrician-killara"],
  "hook":"in the heart of the Upper North Shore",
  "intro":"Pymble homes tend to be substantial and well looked after, and the electrical work needs to keep pace. We plan lighting, data and switchboards for these homes with the future in mind, whether that is an EV charger, a home office or a full renovation.",
  "local":"large homes on generous blocks, with growing demand for EV charging and home offices"},
 {"slug":"electrician-gordon","name":"Gordon","pc":"2072","region":"North Shore",
  "near":["electrician-pymble","electrician-killara","electrician-lindfield","electrician-turramurra"],
  "hook":"a central Upper North Shore suburb",
  "intro":"Gordon sits in the middle of the Upper North Shore rail corridor, a mix of established houses and unit blocks near the station. We cover both: residential upgrades and renovation wiring for the houses, and common-area and maintenance work for the strata blocks.",
  "local":"a mix of established houses and unit blocks around the station"},
 {"slug":"electrician-killara","name":"Killara","pc":"2071","region":"North Shore",
  "near":["electrician-gordon","electrician-lindfield","electrician-pymble","electrician-roseville"],
  "hook":"a quiet, established Upper North Shore suburb",
  "intro":"Killara is large blocks, established homes and long-term owners, and the electrical work reflects that. A lot of these houses are on original or part-updated wiring, so switchboard upgrades, added circuits for renovations, and safe outdoor and pool lighting are the regular jobs. We plan the whole setup rather than patching one fault at a time.",
  "local":"large period and interwar homes on generous, leafy blocks, many mid-renovation"},
 {"slug":"electrician-lindfield","name":"Lindfield","pc":"2070","region":"North Shore",
  "near":["electrician-killara","electrician-roseville","electrician-gordon","electrician-chatswood"],
  "hook":"a leafy suburb in the middle of the Upper North Shore",
  "intro":"Lindfield homes are a mix of solid interwar houses and unit blocks near the station, and both throw up their own electrical work. For the houses it is usually switchboards, reno wiring and lighting; for the units and strata it is common-area and maintenance work. We cover both and sort the paperwork that comes with each.",
  "local":"interwar family homes and station-side unit blocks"},
 {"slug":"electrician-roseville","name":"Roseville","pc":"2069","region":"North Shore",
  "near":["electrician-lindfield","electrician-chatswood","electrician-killara","electrician-artarmon"],
  "hook":"on the lower edge of the Upper North Shore",
  "intro":"Roseville sits between Chatswood and the leafy Upper North Shore, with a lot of well-kept period homes on tree-lined streets. Owners here want work done properly and once, which suits how we quote. Switchboard upgrades, lighting design and EV chargers make up most of what we do.",
  "local":"period homes on tree-lined streets, with a strong renovation market"},
 {"slug":"electrician-st-ives","name":"St Ives","pc":"2075","region":"North Shore",
  "near":["electrician-pymble","electrician-gordon","electrician-turramurra","electrician-belrose"],
  "hook":"the family heart of the Upper North Shore",
  "intro":"St Ives is family-home country, with a lot of homes now at the age where the board, the mains and the lighting are all due attention at once. We are happy to plan that as one job rather than a string of callouts, so it is sorted properly and future-proofed.",
  "local":"established family homes, many due for switchboard and lighting upgrades"},
 {"slug":"electrician-chatswood","name":"Chatswood","pc":"2067","region":"North Shore",
  "near":["electrician-willoughby","electrician-artarmon","electrician-roseville","electrician-lane-cove"],
  "hook":"the North Shore's commercial centre",
  "intro":"Chatswood mixes dense residential with serious commercial activity, so we work both sides here: unit and apartment electrical, and commercial fit-outs, strata common areas and after-hours maintenance for businesses that cannot lose power during trade.",
  "local":"apartments, strata blocks and commercial premises around the town centre"},
 {"slug":"electrician-willoughby","name":"Willoughby","pc":"2068","region":"North Shore",
  "near":["electrician-chatswood","electrician-artarmon","electrician-lane-cove","electrician-roseville"],
  "hook":"a Lower North Shore suburb next to Chatswood",
  "intro":"Willoughby is established houses and semis close to the Chatswood centre, with plenty of renovation and extension work going on. That usually means the board and the wiring need bringing up to scratch at the same time. We plan for what is being added, not just what is there now.",
  "local":"established houses and semis, with a busy renovation and extension market"},
 {"slug":"electrician-lane-cove","name":"Lane Cove","pc":"2066","region":"North Shore",
  "near":["electrician-artarmon","electrician-chatswood","electrician-willoughby"],
  "hook":"a Lower North Shore centre on the river side",
  "intro":"Lane Cove mixes older houses, newer apartments and a busy village centre, so the work ranges from house rewires to strata and small commercial. We cover the residential and the business side, and being a Level 2 provider we can handle the supply and metering that bigger jobs need.",
  "local":"a mix of older houses, apartment blocks and village-centre commercial"},
 {"slug":"electrician-artarmon","name":"Artarmon","pc":"2064","region":"North Shore",
  "near":["electrician-chatswood","electrician-willoughby","electrician-lane-cove","electrician-roseville"],
  "hook":"a Lower North Shore suburb with a commercial and industrial core",
  "intro":"Artarmon is unusual on the North Shore: a settled residential area wrapped around a genuine commercial and light-industrial precinct. We do house and strata work on one side and fit-outs, test and tag and maintenance for the businesses on the other. Both get the same standard.",
  "local":"residential streets around a commercial and light-industrial precinct"},

 # ---------------- NORTHERN BEACHES ----------------
 {"slug":"electrician-manly","name":"Manly","pc":"2095","region":"Northern Beaches",
  "near":["electrician-balgowlah","electrician-freshwater","electrician-seaforth"],
  "hook":"the heart of the Northern Beaches",
  "intro":"Manly is a tight mix of period homes, apartments and the odd commercial strip, all close to salt air that is hard on outdoor wiring and fittings. We do a lot of switchboard work, corrosion-resistant outdoor lighting and strata maintenance here. It is a fair run from base, but we cover it for the right job.",
  "local":"period cottages, apartments and coastal homes exposed to salt air"},
 {"slug":"electrician-balgowlah","name":"Balgowlah","pc":"2093","region":"Northern Beaches",
  "near":["electrician-manly","electrician-seaforth","electrician-freshwater"],
  "hook":"at the Manly end of the Northern Beaches",
  "intro":"Balgowlah is settled family homes across the flat and the Heights, a lot of them mid-renovation. The coastal setting means outdoor lighting and fittings need to be rated for the conditions, and older boards often need upgrading before a reno load goes on. We plan for both.",
  "local":"family homes across Balgowlah and the Heights, many renovating"},
 {"slug":"electrician-seaforth","name":"Seaforth","pc":"2092","region":"Northern Beaches",
  "near":["electrician-balgowlah","electrician-manly","electrician-frenchs-forest"],
  "hook":"between Balgowlah and the Forest",
  "intro":"Seaforth runs from waterfront homes down to established family houses up the hill, so the jobs range from high-end lighting and data to standard switchboard and reno work. The waterfront properties in particular need outdoor wiring done to last in a marine environment.",
  "local":"waterfront and hillside family homes, from high-end to standard stock"},
 {"slug":"electrician-freshwater","name":"Freshwater","pc":"2096","region":"Northern Beaches",
  "near":["electrician-manly","electrician-brookvale","electrician-dee-why"],
  "hook":"a beach suburb between Manly and Curl Curl",
  "intro":"Freshwater is a compact beachside suburb of cottages, semis and newer builds, close enough to the water that salt is a real factor in outdoor and pool wiring. We do switchboard upgrades, coastal-rated outdoor lighting and reno work here, all built to stand up to the conditions.",
  "local":"beachside cottages, semis and newer builds near the water"},
 {"slug":"electrician-dee-why","name":"Dee Why","pc":"2099","region":"Northern Beaches",
  "near":["electrician-brookvale","electrician-narrabeen","electrician-freshwater"],
  "hook":"a central Northern Beaches hub",
  "intro":"Dee Why is one of the denser Beaches suburbs, with a lot of unit and apartment stock alongside houses and a busy commercial strip. That means plenty of strata common-area work and small-business fit-outs and maintenance, as well as the usual residential jobs. We handle the mix.",
  "local":"apartment blocks, houses and a busy commercial centre"},
 {"slug":"electrician-brookvale","name":"Brookvale","pc":"2100","region":"Northern Beaches",
  "near":["electrician-dee-why","electrician-freshwater","electrician-frenchs-forest","electrician-manly"],
  "hook":"the commercial and industrial centre of the Northern Beaches",
  "intro":"Brookvale is where the Beaches does its trade: warehouses, showrooms, workshops and the odd office, wrapped in older housing. We do commercial and light-industrial fit-outs, test and tag and maintenance here, plus the residential work on the streets around it. Being Level 2, we can also handle supply upgrades for bigger loads.",
  "local":"warehouses, showrooms and workshops with older housing around them"},
 {"slug":"electrician-frenchs-forest","name":"Frenchs Forest","pc":"2086","region":"Northern Beaches",
  "near":["electrician-belrose","electrician-seaforth","electrician-brookvale"],
  "hook":"the bushland centre of the Northern Beaches",
  "intro":"Frenchs Forest is family homes on bush blocks plus the hospital and business precinct off the Wakehurst, so we cover residential upgrades and commercial maintenance in the one area. The bush setting means outdoor lighting, longer runs and reliable supply matter more than usual.",
  "local":"family homes on bush blocks near the hospital and business precinct"},
 {"slug":"electrician-belrose","name":"Belrose","pc":"2085","region":"Northern Beaches",
  "near":["electrician-frenchs-forest","electrician-st-ives","electrician-seaforth"],
  "hook":"on the bushland edge of the Northern Beaches, next to St Ives",
  "intro":"Belrose is larger homes on big bush blocks, backing onto the national park, with the retail precinct off Forest Way. Bigger blocks mean longer service runs, more outdoor lighting and often three-phase for the larger homes. We size the supply and the board for what the property actually needs.",
  "local":"large homes on bush blocks backing onto the national park"},
 {"slug":"electrician-narrabeen","name":"Narrabeen","pc":"2101","region":"Northern Beaches",
  "near":["electrician-dee-why","electrician-mona-vale"],
  "hook":"a beach-and-lake suburb on the Northern Beaches",
  "intro":"Narrabeen stretches from the lake to the beach, a mix of older cottages, newer homes and holiday lets. The coastal and waterside exposure is the main electrical factor: outdoor wiring, pool and jetty lighting and boards all need to be rated for it. We do the lot to suit the conditions.",
  "local":"cottages and newer homes between the lake and the beach"},
 {"slug":"electrician-mona-vale","name":"Mona Vale","pc":"2103","region":"Northern Beaches",
  "near":["electrician-narrabeen","electrician-newport"],
  "hook":"a northern hub of the Beaches",
  "intro":"Mona Vale is a service centre for the top of the Beaches, with houses, units, a commercial strip and light industrial nearby. We cover residential upgrades, strata and small-business work here in the one run. The coastal setting makes outdoor and pool wiring a regular part of the job.",
  "local":"houses, units and a commercial centre near the coast"},
 {"slug":"electrician-newport","name":"Newport","pc":"2106","region":"Northern Beaches",
  "near":["electrician-mona-vale","electrician-avalon"],
  "hook":"a peninsula beach suburb",
  "intro":"Newport is beach houses, waterfront homes and older cottages along the peninsula, with plenty of renovation and outdoor-living work. Salt air and pool and jetty wiring are constant considerations, so we spec outdoor fittings and boards to last. It is a long run from base, but worth it for the right job.",
  "local":"beach and waterfront homes with a strong outdoor-living market"},
 {"slug":"electrician-avalon","name":"Avalon","pc":"2107","region":"Northern Beaches",
  "near":["electrician-newport","electrician-mona-vale"],
  "hook":"near the top of the peninsula",
  "intro":"Avalon Beach is a relaxed mix of beach houses, bush-block homes and a village centre, a lot of it built or renovated for indoor-outdoor living. That means outdoor lighting, deck and pool wiring and boards sized for the extra load. We build it to hold up in a coastal, bushy setting.",
  "local":"beach and bush-block homes built around indoor-outdoor living"},

 # ---------------- HILLS DISTRICT ----------------
 {"slug":"electrician-cherrybrook","name":"Cherrybrook","pc":"2126","region":"Hills District",
  "near":["electrician-west-pennant-hills","electrician-pennant-hills","electrician-castle-hill","electrician-dural"],
  "hook":"a leafy Hills District suburb",
  "intro":"Cherrybrook is large, relatively modern family homes on good-sized blocks, many now old enough for their first real electrical upgrade. Switchboards, extra circuits for pools and studios, EV chargers and lighting are the common jobs. We plan for what the household is adding next.",
  "local":"large modern family homes on generous blocks"},
 {"slug":"electrician-west-pennant-hills","name":"West Pennant Hills","pc":"2125","region":"Hills District",
  "near":["electrician-cherrybrook","electrician-pennant-hills","electrician-castle-hill"],
  "hook":"a settled Hills District suburb next to Cherrybrook",
  "intro":"West Pennant Hills is established family homes on leafy streets, close to Cherrybrook and the M2. A lot of the housing is at the age where the board, the mains and the lighting all want attention together, so we quote it as one planned job rather than a series of callouts.",
  "local":"established family homes on leafy, low-traffic streets"},
 {"slug":"electrician-castle-hill","name":"Castle Hill","pc":"2154","region":"Hills District",
  "near":["electrician-cherrybrook","electrician-west-pennant-hills","electrician-dural"],
  "hook":"the centre of the Hills District",
  "intro":"Castle Hill is a big, mixed suburb: large family homes, newer estates, a major town centre and light industrial. We cover residential upgrades and EV chargers, plus commercial fit-outs and maintenance around the centre. Being Level 2, we can handle the supply upgrades the bigger homes and jobs need.",
  "local":"large family homes, newer estates and a major commercial centre"},
 {"slug":"electrician-dural","name":"Dural","pc":"2158","region":"Hills District",
  "near":["electrician-cherrybrook","electrician-castle-hill"],
  "hook":"on the rural edge of the Hills District",
  "intro":"Dural is acreage and large blocks, which changes the electrical work: longer service runs, sheds and studios needing their own supply, three-phase for pumps and machinery, and plenty of outdoor lighting. As a Level 2 provider we can sort the supply side as well as the wiring, so it is one team for the whole property.",
  "local":"acreage and large blocks, with sheds, studios and three-phase demand"},
]
SB_BY_SLUG={sb["slug"]:sb for sb in SUBURBS}
REGIONS=["North Shore","Northern Beaches","Hills District"]

# =========================================================
# HOMEOWNER SERVICE PAGES
# Granular, home-focused service pages that sit under the Homeowners menu at
# /homeowners/<slug>/. Same rich structure as SERVICES. Written for the
# homeowner, not the builder or business. Three of these (ev-charger,
# outdoor-lighting, emergency) overlap a broader /services/ page: the "cross"
# key links to that page and the copy is kept home-only to avoid competing for
# the same searches.
# =========================================================
HOME_SERVICES = [
 {"slug":"electrical-repairs","name":"Electrical Repairs","icon":"home","img":"electrical-repairs-hero.jpg","focus":"center 30%",
  "card":"Flickering lights, dead power points, tripping breakers or a fault you can't find. We diagnose it and fix it properly.",
  "h1":"Electrical repairs for your home, done properly the first time.",
  "hero":"Flickering lights, dead power points, a breaker that keeps tripping or a fault you just can't track down. Torraca Electrical finds the cause and fixes it right, across Hornsby and the North Shore.",
  "stype":"Residential Electrical Repairs",
  "title":"Electrical Repairs Hornsby | Home Fault Finding | Torraca Electrical",
  "meta":"Licensed electrical repairs for homes across Hornsby and the North Shore. Fault finding, dead power points, tripping breakers and flickering lights, sorted. Call today.",
  "intro":[
    "When something electrical stops working at home, you want it looked at by someone who will find the actual cause, not just patch the symptom. Torraca Electrical does proper fault finding: we track the problem back to its source, explain what we find in plain terms, and fix it so it stays fixed.",
    "Most home repairs are sorted in a single visit. Where a fault points to something bigger, like a tired switchboard or ageing wiring, we tell you straight and give you the options rather than papering over it. Every repair is backed by our 12-month workmanship warranty."],
  "groups":[
    ("Common home faults",["Power points that are dead, warm or sparking","Light fittings and switches that have stopped working","Circuit breakers or safety switches that keep tripping","Flickering or dimming lights","Buzzing switches, fittings or the switchboard"]),
    ("Fault finding and diagnosis",["Tracing intermittent and hard-to-find faults","Isolating which circuit is causing the problem","Testing power points, circuits and connections","Sorting whether it's your fault or a network supply issue","Clear explanation of what's wrong and what it takes to fix"]),
    ("Repairs and rectification",["Replacing failed switches, outlets and fittings","Repairing damaged or overloaded circuits","Fixing dodgy DIY or previous trade work","Rectifying defects flagged in an inspection report","Making unsafe wiring safe"])],
  "edu_h":"When should you call an electrician for a repair?",
  "edu_intro":"Some electrical faults are a nuisance, others are an early warning. Call a licensed electrician if you notice:",
  "edu_list":["A power point that feels warm, sparks, or has scorch marks","Lights that flicker or dim for no obvious reason","A safety switch or breaker that keeps tripping","A burning smell near a fitting, switch or the switchboard","Power points or switches that only work sometimes","Anything that gives you even a small tingle when you touch it"],
  "edu_close":"If a fitting is sparking or you can smell burning, switch that circuit off at the board and call us straight away. For anything less urgent, book a visit and we'll get it sorted."},

 {"slug":"switchboard-upgrades","name":"Switchboard Upgrades","icon":"board","img":"switchboard-upgrades-hero.jpg","focus":"center 45%",
  "card":"Old ceramic fuses or no safety switches? We upgrade your switchboard to modern breakers and RCDs, ready for today's loads.",
  "h1":"Switchboard upgrades that bring your home up to standard.",
  "hero":"Ceramic fuses, no safety switches, or a board that trips every time the kettle and heater run together. Torraca Electrical upgrades home switchboards across Hornsby and the North Shore to modern, safe, compliant standards.",
  "stype":"Switchboard Upgrade",
  "title":"Switchboard Upgrades Hornsby | Home Switchboard Replacement | Torraca Electrical",
  "meta":"Home switchboard upgrades across Hornsby and the North Shore. Modern breakers, safety switches and compliant boards, sized for today's loads. Call Torraca Electrical.",
  "intro":[
    "Your switchboard is the heart of your home's electrical system, and a lot of North Shore homes are still running boards that were never designed for modern loads. Old ceramic fuses, no safety switches, and not enough circuits to go around are all signs it's time for an upgrade.",
    "We assess what you've got, size the new board for how you actually use the home now and where you're heading, then install it cleanly and test every circuit. Because we're a Level 2 provider, if the upgrade also needs the incoming supply or consumer mains lifted, we handle that in the same visit instead of subbing it out. Backed by our 12-month workmanship warranty."],
  "groups":[
    ("Switchboard upgrades and replacement",["Full switchboard replacement","Ceramic fuse to circuit breaker upgrades","Adding safety switches (RCDs) to every circuit","Extra circuits for renovations and added rooms","Neat, labelled boards that are easy to work with"]),
    ("Safety and compliance",["Bringing the board up to current AS/NZS 3000 standards","Surge protection at the board","Correct circuit separation and RCD protection","Compliance certificate on completion","Rectifying defects flagged by an inspector or insurer"]),
    ("Supply and capacity (Level 2)",["Consumer mains upgrades where the board needs more supply","Single phase to three phase conversions","Capacity for EV chargers, air con and induction cooking","Meter box relocation and upgrades","All Ausgrid paperwork handled in-house"])],
  "edu_h":"How do you know your switchboard needs upgrading?",
  "edu_intro":"A switchboard upgrade is one of the best-value safety investments in an older home. Look at yours if:",
  "edu_list":["It still uses ceramic fuses or rewireable fuse wire","There are no safety switches (RCDs) protecting the circuits","It trips whenever a few appliances run at once","It's rusty, crowded, or has no room for another circuit","You're adding an EV charger, air con, or renovating","The board is more than 15 to 20 years old"],
  "edu_close":"A typical home switchboard upgrade starts around $4,000 depending on scope. We'll assess yours and give you a clear, itemised quote before any work starts."},

 {"slug":"led-lighting","name":"LED Lighting","icon":"bulb","img":"led-lighting-hero.jpg","focus":"center 40%",
  "card":"Downlights, replacements and full lighting plans. Brighter, cheaper to run, and installed to last, not to fail in two years.",
  "h1":"LED lighting that looks better and costs less to run.",
  "hero":"Swapping tired halogens for LED, planning downlights for a reno, or fixing lights that keep failing. Torraca Electrical designs and installs home LED lighting across Hornsby and the North Shore.",
  "stype":"LED Lighting Installation",
  "title":"LED Lighting Hornsby | Home Downlights and Upgrades | Torraca Electrical",
  "meta":"Home LED lighting and downlight installation across Hornsby and the North Shore. Lower running costs, better light, installed to last. Call Torraca Electrical for a quote.",
  "intro":[
    "Good lighting changes how a home feels, and switching to LED cuts your running costs while you're at it. The catch is that cheap fittings and rushed installs are why so many downlights flicker or die early. We use quality fittings, place them properly, and wire them to last.",
    "Whether it's a straight swap of old halogens, a fresh downlight layout for a renovation, or dimmers and zones to set the mood, we'll plan it around the room and how you use it. Done once, done right, and covered by our 12-month workmanship warranty."],
  "groups":[
    ("Downlights and replacements",["Halogen to LED downlight conversions","New downlight layouts for renovations","Pendant, batten and feature light installation","Dimmable LED setups and dimmer installation","Replacing failed or flickering fittings"]),
    ("Lighting design and control",["Room-by-room lighting plans","Warm or cool colour temperature selection","Zones and dimming for living areas","Smart and app-controlled lighting","Sensor lighting for hallways, robes and garages"]),
    ("Kitchens, bathrooms and outdoors",["Kitchen task and under-cabinet lighting","IP-rated fittings for bathrooms and wet areas","Wardrobe and cabinet lighting","Undercover alfresco and patio lighting","Exhaust fan and light combinations"])],
  "edu_h":"Is it worth upgrading to LED?",
  "edu_intro":"For most homes, yes. LED uses far less power, lasts years longer, and runs cool. It's worth doing if:",
  "edu_list":["You still have halogen downlights that run hot and cost a fortune","Bulbs and fittings keep blowing or flickering","You're renovating and want the lighting planned properly","Rooms feel too dark, too harsh, or unevenly lit","You want dimming or zones for living and bedroom areas","You'd like lower power bills without losing brightness"],
  "edu_close":"We'll look at what you've got, tell you what's worth changing and what isn't, and quote it clearly. No pressure to replace what's fine."},

 {"slug":"safety-switches","name":"Safety Switches","icon":"shield","img":"safety-switches-hero.jpg","focus":"center 35%",
  "card":"Safety switches (RCDs) cut the power in milliseconds to stop a shock becoming fatal. We install and test them properly.",
  "h1":"Safety switches that protect your family, installed and tested right.",
  "hero":"A safety switch cuts the power in a fraction of a second when something goes wrong, and every home should have them on every circuit. Torraca Electrical installs and tests RCDs across Hornsby and the North Shore.",
  "stype":"Safety Switch Installation",
  "title":"Safety Switch Installation Hornsby | RCD Installation | Torraca Electrical",
  "meta":"Safety switch (RCD) installation and testing for homes across Hornsby and the North Shore. Protect every circuit, meet compliance, stay safe. Call Torraca Electrical.",
  "intro":[
    "A safety switch, or RCD, is the one device that can stop an electric shock from being fatal. It detects a fault and cuts the power in milliseconds, well before a person or your wiring is harmed. A surprising number of North Shore homes still have them on only some circuits, or none at all.",
    "We install RCDs correctly at the switchboard, make sure every circuit that should be protected is protected, and test that they actually trip the way they're meant to. If your board is too old to take them, we'll tell you what an upgrade involves. Covered by our 12-month workmanship warranty."],
  "groups":[
    ("Safety switch installation",["RCDs added to every power and lighting circuit","Combined RCD and circuit breaker (RCBO) installation","Retrofitting safety switches to older boards","Dedicated protection for wet areas and outdoor circuits","Compliance certificate on completion"]),
    ("Testing and compliance",["Push-button and trip-time testing","Checking existing RCDs actually work","Testing after a fault or nuisance tripping","Compliance for sales, rentals and insurance","Written record of results"]),
    ("Fault finding on tripping RCDs",["Finding what's causing a safety switch to trip","Isolating the faulty appliance or circuit","Repairing the underlying fault, not just the reset","Advice on nuisance tripping versus a real fault","Upgrading boards too old to take an RCD"])],
  "edu_h":"Does your home have proper safety switch protection?",
  "edu_intro":"Not all homes do, and older ones often have gaps. You should have safety switches checked if:",
  "edu_list":["Your switchboard still uses fuses or has no visible test buttons","Only some circuits are protected, not all of them","You've never tested the switches, or don't know how","A safety switch keeps tripping for no clear reason","You're buying, selling, or renting out the property","The home hasn't had an electrical check in years"],
  "edu_close":"Testing your safety switches is quick and cheap, and installing them where they're missing is one of the most important electrical jobs in any home. Give us a call and we'll sort it."},

 {"slug":"smoke-alarms","name":"Smoke Alarms","icon":"alert","img":"smoke-alarms-hero.jpg","focus":"center 40%",
  "card":"Hard-wired, interconnected photoelectric smoke alarms installed and tested to keep your home compliant and your family safe.",
  "h1":"Smoke alarms installed, interconnected and compliant.",
  "hero":"Smoke alarms that are hard-wired, interconnected and where they need to be. Torraca Electrical installs and tests photoelectric smoke alarms for homes across Hornsby and the North Shore.",
  "stype":"Smoke Alarm Installation",
  "title":"Smoke Alarm Installation Hornsby | Hard-Wired and Interconnected | Torraca Electrical",
  "meta":"Hard-wired, interconnected smoke alarm installation for homes across Hornsby and the North Shore. Photoelectric, compliant and tested. Call Torraca Electrical.",
  "intro":[
    "Smoke alarms are the cheapest life-saving device in your home, and the rules on them have tightened. Hard-wired, interconnected photoelectric alarms are the standard to aim for: when one goes off, they all go off, so everyone gets warning wherever they are in the house.",
    "We install alarms in the right rooms and positions, wire them back to mains power with a battery backup, and interconnect them so they work as one system. We also test and replace ageing alarms, which are only rated to last around ten years. Backed by our 12-month workmanship warranty."],
  "groups":[
    ("Installation and interconnection",["Hard-wired 240V photoelectric alarms","Wireless and hard-wired interconnection","Correct placement in bedrooms, halls and living areas","Battery backup on every alarm","Replacing expired or beeping alarms"]),
    ("Compliance and landlords",["Meeting current NSW smoke alarm requirements","Alarms for sales, rentals and insurance","Compliance for property managers and landlords","Photoelectric upgrades from old ionisation units","Written record of installation and testing"]),
    ("Testing and maintenance",["Testing existing alarms and interconnection","Checking alarm age and replacing at end of life","Sorting alarms that beep or false-trigger","Advice on how many alarms and where","Adding alarms during a reno or extension"])],
  "edu_h":"When should smoke alarms be replaced?",
  "edu_intro":"Smoke alarms don't last forever, and a lot of homes are running expired units. Have yours looked at if:",
  "edu_list":["Any alarm is more than 10 years old (check the date on it)","Your alarms are battery-only rather than hard-wired","The alarms aren't interconnected so only one sounds","You've still got old ionisation alarms rather than photoelectric","An alarm keeps chirping or going off for no reason","You're renting the property out and need it compliant"],
  "edu_close":"If your alarms are old or you're not sure they'd all sound in a fire, book a check. It's a small job that matters more than almost any other."},

 {"slug":"ev-charger","name":"EV Charger","icon":"ev","img":"ev-charger-hero.jpg","focus":"center 45%",
  "card":"A home EV charger installed properly, with the switchboard checked so your car charges safely at full speed overnight.",
  "h1":"Home EV charger installation, done right.",
  "hero":"Charge at home overnight, safely and at full speed. Torraca Electrical installs home EV chargers across Hornsby and the North Shore, all brands, with the switchboard checked first.",
  "stype":"Home EV Charger Installation",
  "title":"Home EV Charger Installation Hornsby | Torraca Electrical",
  "meta":"Home EV charger installation across Hornsby and the North Shore. All brands, switchboard assessed, installed safely at full charging speed. Call Torraca Electrical.",
  "intro":[
    "Charging at home is the whole point of an EV, and getting the charger installed properly is what makes it safe and fast. Torraca Electrical installs home wall chargers of every brand, and because DIY EV wiring is illegal, this is a job for a licensed electrician anyway.",
    "We start by checking your switchboard can take the extra load, run a dedicated circuit to wherever the car parks, mount the charger neatly, and set it up so it charges overnight on your cheapest tariff. Where the board or supply needs lifting first, being Level 2 means we handle that too. Covered by our 12-month workmanship warranty."],
  "groups":[
    ("Home charger installation",["Wall-mounted AC chargers, all brands","Tesla, Wallbox, Ocular, Zappi and more","Garage, carport and driveway mounting","Dedicated 32A circuit to the charging point","Smart charger setup and app configuration"]),
    ("Switchboard and supply",["Switchboard capacity check before install","Board upgrades to carry the extra load","Single phase to three phase where needed (Level 2)","Load management so nothing overloads","Tidy cable runs, inside or out"]),
    ("Charging smart",["Setting the charger to off-peak tariffs","Scheduling and app-based control","Future-proofing for a second EV","Solar-friendly setups where you have panels","Advice on the right charger for your car and use"])],
  "edu_h":"What's involved in a home EV charger install?",
  "edu_intro":"Most homes can take a charger, but a few things need checking first. Here's what's typically involved:",
  "edu_list":["A licensed electrician is required by law, DIY is illegal","Your switchboard may need capacity checked or upgraded","A dedicated circuit runs from the board to the charger","Most homes suit a 7kW single-phase charger","Three-phase homes can charge faster if the car supports it","Smart chargers can be set to run on off-peak power"],
  "edu_close":"Not sure what your home can take? We offer a free assessment and clear quote. Just get in touch.",
  "cross":("ev-charger-installation","EV charger installation for business and strata","Fitting out a workplace, carpark or strata building? See our")},

 {"slug":"ceiling-fans","name":"Ceiling Fans","icon":"compass","img":"ceiling-fans-hero.jpg","focus":"center 30%",
  "card":"Ceiling fans supplied and installed, or your fan swapped and wired to a proper controller. Balanced, quiet, done right.",
  "h1":"Ceiling fans installed and wired properly.",
  "hero":"A new fan supplied and fitted, or an old one swapped out and wired to a proper controller. Torraca Electrical installs ceiling fans across Hornsby and the North Shore.",
  "stype":"Ceiling Fan Installation",
  "title":"Ceiling Fan Installation Hornsby | Supply and Install | Torraca Electrical",
  "meta":"Ceiling fan installation across Hornsby and the North Shore. Supplied and fitted or swapped, wired to proper controls, balanced and quiet. Call Torraca Electrical.",
  "intro":[
    "A ceiling fan is one of the cheapest ways to make a room comfortable year-round, but it has to be mounted to something solid and wired correctly or you end up with a wobble, a hum, or a fan that won't run properly. We install fans that are balanced, quiet and safely fixed.",
    "We can supply and fit a fan to suit the room, or install one you've already bought, including fan and light combinations and models with wall or remote controls. If there's no existing point, we'll run the wiring and add the switch. Backed by our 12-month workmanship warranty."],
  "groups":[
    ("Supply and installation",["Ceiling fans supplied to suit the room","Installing a fan you've already bought","Fan and light combination units","Replacing old or noisy fans","Outdoor and undercover patio fans (IP-rated)"]),
    ("Wiring and controls",["Wall speed controllers and switches","Remote and app-controlled fans","Adding a new fan point where there isn't one","Separate switching for fan and light","Reverse-cycle winter mode setup"]),
    ("Mounting done right",["Fixing to a solid, rated mounting point","Balancing so there's no wobble","Sorting fans that hum or run slow","Correct blade height and clearance advice","Tidy, safe finish every time"])],
  "edu_h":"Should a ceiling fan be installed by an electrician?",
  "edu_intro":"Yes. Wiring and mounting a fan is licensed electrical work, and doing it wrong causes wobble, noise or worse. Call us when:",
  "edu_list":["You're adding a fan where there's no existing point","An old fan is wobbling, humming or running slowly","You want a fan and light combo on separate switches","You'd like remote or wall speed control","The room is outdoors or undercover and needs a rated fan","You've bought a fan and want it fitted safely"],
  "edu_close":"Whether it's one fan or fans through the whole house, we'll get them up, balanced and running quietly. Give us a call."},

 {"slug":"power-points","name":"Power Points","icon":"data","img":"power-points-hero.jpg","focus":"center 48%",
  "card":"Extra power points, USB outlets and outdoor GPOs added where you actually need them. No more double adaptors and lead runs.",
  "h1":"Extra power points, exactly where you need them.",
  "hero":"More outlets, USB points, and outdoor power where the double adaptors and extension leads currently live. Torraca Electrical adds power points for homes across Hornsby and the North Shore.",
  "stype":"Power Point Installation",
  "title":"Power Point Installation Hornsby | Extra GPOs and USB Outlets | Torraca Electrical",
  "meta":"Power point installation across Hornsby and the North Shore. Extra GPOs, USB outlets and outdoor power added safely where you need them. Call Torraca Electrical.",
  "intro":[
    "Running out of outlets is one of the most common jobs we get, and it's worth doing properly rather than living with double adaptors and leads across the floor. We add power points where you actually use power: behind the TV, across a benchtop, in the garage, or out on the deck.",
    "New outlets are wired back to the board on the right circuit, so you're not overloading an existing one, and outdoor points are weatherproof and RCD-protected. Small job or a whole house of extra outlets during a reno, it's covered by our 12-month workmanship warranty."],
  "groups":[
    ("Indoor power points",["Extra double and single GPOs","USB and USB-C combination outlets","Kitchen benchtop and appliance points","Behind-TV and media wall outlets","Garage, laundry and study points"]),
    ("Outdoor and special outlets",["Weatherproof outdoor GPOs","Power for sheds, studios and pergolas","Dedicated circuits for heavy appliances","Points for pool, spa and pump equipment","Floor and skirting outlets"]),
    ("Done safely",["Wired to the correct circuit, not an overloaded one","RCD protection on new circuits","Neat cable runs and clean finish","Moving awkwardly placed existing points","Replacing worn, cracked or warm outlets"])],
  "edu_h":"When is it time to add power points?",
  "edu_intro":"If your home was wired years ago, it almost certainly has fewer outlets than modern life needs. It's worth adding points when:",
  "edu_list":["You're relying on double adaptors and power boards","Extension leads are running between rooms","There's no power where you've set up a desk or TV","The kitchen or laundry is short on benchtop outlets","You want weatherproof power outside","An existing outlet is cracked, worn or feels warm"],
  "edu_close":"Adding outlets is quick and inexpensive, and it clears the clutter and the safety risk of overloaded boards. Tell us where you need power and we'll sort it."},

 {"slug":"outdoor-lighting","name":"Outdoor Lighting","icon":"tree","img":"outdoor-lighting-hero.jpg","focus":"center 45%",
  "card":"Garden, path, deck and security lighting for your home. Wired to last outdoors, RCD-protected, and set on timers or sensors.",
  "h1":"Outdoor lighting that makes your home safer and better to live in.",
  "hero":"Path and garden lights, deck and entertaining areas, and sensor security lighting. Torraca Electrical designs and installs home outdoor lighting across Hornsby and the North Shore.",
  "stype":"Home Outdoor Lighting",
  "title":"Outdoor Lighting Hornsby | Home Garden and Security Lighting | Torraca Electrical",
  "meta":"Home outdoor lighting across Hornsby and the North Shore. Garden, path, deck and sensor security lighting, wired to last and RCD-protected. Call Torraca Electrical.",
  "intro":[
    "Outdoor lighting does two jobs at once: it makes your home safer to come home to, and it makes the garden and entertaining areas usable after dark. The trick is fittings and wiring rated for weather and installed to last, because outdoor is where cheap jobs fail fastest.",
    "We plan the lighting around how you use the space, from subtle path and garden lights to bright, sensor-triggered security lighting. Everything outdoors is weather-rated, RCD-protected and can run on timers or sensors so it looks after itself. Covered by our 12-month workmanship warranty."],
  "groups":[
    ("Garden and path lighting",["Garden bed and feature uplighting","Path, step and driveway lighting","Low-voltage garden lighting systems","Timer and dusk-to-dawn controls","Warm, low-glare fittings for the evening"]),
    ("Deck and entertaining",["Deck, patio and pergola lighting","Alfresco and outdoor kitchen lighting","Wall and step lights for stairs and levels","Festoon and feature lighting wiring","Weatherproof switching and control"]),
    ("Security lighting",["Motion-sensor security floodlights","Driveway and perimeter lighting","Front-door and entry lighting","Smart and app-controlled outdoor lights","Sensor setup to avoid false triggers"])],
  "edu_h":"Why use a licensed electrician for outdoor lighting?",
  "edu_intro":"Outdoor electrical work faces weather, water and underground cabling, so it carries risks indoor work doesn't. Getting it wrong can void your insurance. It matters because:",
  "edu_list":["Outdoor circuits must be RCD-protected","Fittings must be rated for weather exposure (IP rating)","Underground cabling must be laid and protected correctly","Poolside and wet-area lighting has strict rules","Bad outdoor wiring is a shock and fire risk","Only a licensed electrician can legally install fixed outdoor wiring"],
  "edu_close":"We'll make sure your outdoor lighting looks the part and is completely safe and compliant. Tell us what you're picturing and we'll take it from there.",
  "cross":("landscape-lighting","full landscape and feature lighting service","Larger garden, pool or feature lighting project? See our")},

 {"slug":"rewiring","name":"Rewiring","icon":"bolt","img":"rewiring-hero.jpg","focus":"center 50%",
  "card":"Old, brittle or unsafe wiring replaced. Full or partial home rewires, planned around you, with minimal mess and disruption.",
  "h1":"Rewiring that makes an older home safe again.",
  "hero":"Old cloth or brittle wiring, not enough circuits, and repairs that keep coming back. Torraca Electrical handles full and partial home rewires across Hornsby and the North Shore.",
  "stype":"Home Rewiring",
  "title":"House Rewiring Hornsby | Full and Partial Rewires | Torraca Electrical",
  "meta":"Full and partial house rewiring across Hornsby and the North Shore. Old wiring replaced safely, planned around you, minimal mess. Call Torraca Electrical.",
  "intro":[
    "Wiring doesn't last forever. Older North Shore homes often still have decades-old cabling that's gone brittle, was never earthed properly, or simply can't cope with how much we plug in now. Rewiring replaces it with modern, safe cable and gives you the circuits a current home needs.",
    "A rewire sounds daunting, but done well it's methodical and tidy. We plan it in stages around you, keep the mess and disruption down, and make good as we go. Being Level 2, we can upgrade the switchboard and supply at the same time so it's one team, one job. Backed by our 12-month workmanship warranty."],
  "groups":[
    ("Full and partial rewires",["Whole-home rewiring","Partial rewires for older sections or extensions","Replacing brittle, cloth or unearthed wiring","Rewiring during a renovation","Adding circuits for modern loads"]),
    ("Planning and minimal disruption",["Staged work so you keep power where possible","Cable runs planned to reduce wall damage","Making good and tidy reinstatement","Clear scope and timeline up front","Coordination with builders on renos"]),
    ("Switchboard and supply (Level 2)",["New switchboard as part of the rewire","Consumer mains and supply upgrades","Single phase to three phase where needed","Full RCD and surge protection","Compliance certificate on completion"])],
  "edu_h":"How do you know a home needs rewiring?",
  "edu_intro":"Rewiring is a bigger job, so it's worth knowing the signs. Consider it if:",
  "edu_list":["The home still has old cloth-covered or rubber wiring","There's no earth on some circuits or outlets","Repairs and faults keep recurring in the same areas","The home is 40-plus years old and never rewired","You're renovating and opening up walls anyway","Lights dim and circuits overload with normal use"],
  "edu_close":"Not every old home needs a full rewire, and we'll tell you honestly whether a partial job or targeted repairs will do instead. Book an assessment and we'll give you the straight version."},

 {"slug":"surge-protection","name":"Surge Protection","icon":"shield","img":"surge-protection-hero.jpg","focus":"center 35%",
  "card":"Whole-home surge protection at the switchboard to guard your appliances and electronics from spikes and storm damage.",
  "h1":"Surge protection that guards your appliances and electronics.",
  "hero":"One power spike can take out a fridge, a TV and every charger in the house. Torraca Electrical fits whole-home surge protection at the switchboard across Hornsby and the North Shore.",
  "stype":"Surge Protection Installation",
  "title":"Surge Protection Hornsby | Whole-Home Surge Protection | Torraca Electrical",
  "meta":"Whole-home surge protection installed at the switchboard across Hornsby and the North Shore. Guard appliances and electronics from spikes. Call Torraca Electrical.",
  "intro":[
    "Modern homes are full of electronics that don't like power spikes: fridges, TVs, computers, solar inverters, and every device on a charger. A surge from a storm, the grid, or a fault can wipe them out in an instant, and it's rarely covered the way people assume.",
    "A surge protection device fitted at your switchboard clamps those spikes before they reach your circuits, protecting the whole home from one point. We fit it as part of a switchboard upgrade or as a standalone job on a compatible board, and being Level 2 we can also address supply-side issues that cause surges. Covered by our 12-month workmanship warranty."],
  "groups":[
    ("Whole-home protection",["Surge protection device fitted at the switchboard","Protection across every circuit from one point","Fitted with a switchboard upgrade or on its own","Correct device rating for your board","Compliance and correct installation"]),
    ("Sensitive equipment",["Extra protection for home offices and AV gear","Guarding solar inverters and battery systems","Protection for medical and essential equipment","Point-of-use protection where it's warranted","Advice on what's worth protecting"]),
    ("Storm and supply issues",["Protection ahead of storm season","Addressing repeated spikes and flickers","Checking earthing that makes surges worse","Supply-side fault investigation (Level 2)","Advice after appliances have been damaged"])],
  "edu_h":"Do you need surge protection?",
  "edu_intro":"If your home runs on more than lights and a kettle, it's worth having. Consider it if:",
  "edu_list":["You've lost appliances or electronics to a spike before","You're in an area that gets decent storms","You have solar, a battery, or a home office setup","You've just upgraded the switchboard anyway","Lights flicker or dim when big appliances kick in","You want cheap insurance for expensive gear"],
  "edu_close":"Surge protection is inexpensive next to the equipment it protects. We'll check whether your board can take a device and fit one that suits. Give us a call."},

 {"slug":"emergency","name":"24/7 Emergency","icon":"alert","img":"emergency-hero.jpg","focus":"center 32%","emergency":True,
  "card":"Power out, sparking, or a burning smell at home? We answer 24/7 across the North Shore and make it safe, fast.",
  "h1":"Home electrical emergency? We're on call right now.",
  "hero":"Power out, sparking, or a burning smell at home? Torraca Electrical answers 24 hours a day, 7 days a week for urgent home electrical emergencies across Hornsby and the North Shore.",
  "stype":"Emergency Electrical Services",
  "title":"Emergency Electrician Hornsby | 24/7 Home Callout | Torraca Electrical",
  "meta":"24/7 emergency electrician for homes across Hornsby and the North Shore. Power outages, sparking, burning smells and safety hazards, made safe fast. Call now.",
  "intro":[
    "When something goes wrong with the power at home, you want someone who answers and can make it safe quickly. Torraca Electrical runs an after-hours emergency service, 24 hours a day, 7 days a week including weekends and public holidays, across Hornsby and the North Shore.",
    "We'll get to you, make the situation safe, and restore power where we can. If it's a network supply fault rather than something inside the home, being Level 2 means we can often deal with that too instead of leaving you waiting on someone else."],
  "groups":[
    ("Power loss and tripping",["Complete power outage at the home","Safety switch or breaker that won't reset","Overloaded circuits tripping repeatedly","Working out if it's your fault or the network's","Restoring power safely"]),
    ("Hazards and safety",["Sparking or arcing power points and switches","Burning smell from a fitting or the switchboard","Exposed or damaged wiring","After a minor shock from an appliance or outlet","Signs of an electrical fire"]),
    ("Storm and after-hours",["Storm damage to the switchboard or service line","Water getting into electrical fittings","Fallen or damaged service line to the house (Level 2)","After-hours repairs for the home","Temporary supply where it's needed"])],
  "edu_h":"What counts as an electrical emergency at home?",
  "edu_intro":"If you're not sure, treat it as one and call. Ring us straight away if you have:",
  "edu_list":["Total loss of power with no obvious cause","Sparking, arcing or burning from any fitting","A burning smell you can't explain","Had an electric shock, however minor","A safety switch that keeps tripping and won't hold","Storm damage to your meter box or service line"],
  "edu_close":"While you wait: switch off the affected circuit at the board if it's safe to reach, keep clear of any damaged wiring, and if you can smell burning or see smoke, get everyone out and call 000 first.",
  "cross":("emergency-electrician","emergency service for business and strata","Need urgent help at a workplace or managed building? See our")},
]
HOME_BY_SLUG={s["slug"]:s for s in HOME_SERVICES}

print("content loaded:", len(SERVICES), "services,", len(HOME_SERVICES), "home services,", len(SUBURBS), "suburbs")
